package cc.grzx.dao;

import cc.grzx.entity.User;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @Insert({
        "insert into user (id, nickname, ",
        "fullname, phone, ",
        "sex, born_date, ",
        "address, head_img, ",
        "create_time, create_by, ",
        "update_time, update_by, ",
        "grade)",
        "values (#{id,jdbcType=INTEGER}, #{nickname,jdbcType=VARCHAR}, ",
        "#{fullname,jdbcType=VARCHAR}, #{phone,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=VARCHAR}, #{bornDate,jdbcType=TIMESTAMP}, ",
        "#{address,jdbcType=VARCHAR}, #{headImg,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=TIMESTAMP}, #{updateBy,jdbcType=INTEGER}, ",
        "#{grade,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @Select({
        "select",
        "id, nickname, fullname, phone, sex, born_date, address, head_img, create_time, ",
        "create_by, update_time, update_by, grade",
        "from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results(id="userMap",value={
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="nickname", property="nickname", jdbcType=JdbcType.VARCHAR),
        @Result(column="fullname", property="fullname", jdbcType=JdbcType.VARCHAR),
        @Result(column="phone", property="phone", jdbcType=JdbcType.VARCHAR),
        @Result(column="sex", property="sex", jdbcType=JdbcType.VARCHAR),
        @Result(column="born_date", property="bornDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="head_img", property="headImg", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.INTEGER),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_by", property="updateBy", jdbcType=JdbcType.INTEGER),
        @Result(column="grade", property="grade", jdbcType=JdbcType.VARCHAR)
    })
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Apr 28 22:08:22 CST 2020
     */
    @Update({
        "update user",
        "set nickname = #{nickname,jdbcType=VARCHAR},",
          "fullname = #{fullname,jdbcType=VARCHAR},",
          "phone = #{phone,jdbcType=VARCHAR},",
          "sex = #{sex,jdbcType=VARCHAR},",
          "born_date = #{bornDate,jdbcType=TIMESTAMP},",
          "address = #{address,jdbcType=VARCHAR},",
          "head_img = #{headImg,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP},",
          "update_by = #{updateBy,jdbcType=INTEGER},",
          "grade = #{grade,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
    
  //查询所有的用户信息
    @Select({
        "select",
        "id, nickname, fullname, phone, sex, born_date, address, head_img, create_time, ",
        "create_by, update_time, update_by",
        "from user",
    })
    @ResultMap("userMap")
    List<User> selectAll();
}