package cc.sjzd.entity;

public class PracticeType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_type.id
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_type.type_name
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_type.id
     *
     * @return the value of practice_type.id
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_type.id
     *
     * @param id the value for practice_type.id
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_type.type_name
     *
     * @return the value of practice_type.type_name
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_type.type_name
     *
     * @param typeName the value for practice_type.type_name
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
    
}