package cc.sjzd.entity;

import java.util.Date;
import java.util.List;

public class PracticeInstitute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.center_name
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String instituteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.create_time
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.address
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.manager
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.phone
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.intro
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.type_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.center_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private Integer centerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_institute.imgs
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    private String imgs;
    
    private List<PracticeStation> stations;
    

    public List<PracticeStation> getStations() {
		return stations;
	}

	public void setStations(List<PracticeStation> stations) {
		this.stations = stations;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.id
     *
     * @return the value of practice_institute.id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.id
     *
     * @param id the value for practice_institute.id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.center_name
     *
     * @return the value of practice_institute.center_name
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getInstituteName() {
        return instituteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.center_name
     *
     * @param centerName the value for practice_institute.center_name
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setInstituteName(String instituteName) {
        this.instituteName = instituteName == null ? null : instituteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.create_time
     *
     * @return the value of practice_institute.create_time
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.create_time
     *
     * @param createTime the value for practice_institute.create_time
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.address
     *
     * @return the value of practice_institute.address
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.address
     *
     * @param address the value for practice_institute.address
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.manager
     *
     * @return the value of practice_institute.manager
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.manager
     *
     * @param manager the value for practice_institute.manager
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.phone
     *
     * @return the value of practice_institute.phone
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.phone
     *
     * @param phone the value for practice_institute.phone
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.intro
     *
     * @return the value of practice_institute.intro
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.intro
     *
     * @param intro the value for practice_institute.intro
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.type_id
     *
     * @return the value of practice_institute.type_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.type_id
     *
     * @param typeId the value for practice_institute.type_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.center_id
     *
     * @return the value of practice_institute.center_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public Integer getCenterId() {
        return centerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.center_id
     *
     * @param centerId the value for practice_institute.center_id
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setCenterId(Integer centerId) {
        this.centerId = centerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_institute.imgs
     *
     * @return the value of practice_institute.imgs
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_institute.imgs
     *
     * @param imgs the value for practice_institute.imgs
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

	public PracticeInstitute() {
		super();
	}

	public PracticeInstitute(String instituteName, Date createTime, String address, String manager, String phone,
			String intro, Integer typeId, Integer centerId, String imgs) {
		super();
		this.instituteName = instituteName;
		this.createTime = createTime;
		this.address = address;
		this.manager = manager;
		this.phone = phone;
		this.intro = intro;
		this.typeId = typeId;
		this.centerId = centerId;
		this.imgs = imgs;
	}
	
    
}