package cc.sjzd.entity;

import java.util.Date;
import java.util.List;

public class PracticeCenter{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
	
    private Integer id;

    public PracticeCenter() {
		super();
	}

	public PracticeCenter(String centerName, Date createTime, String address, String manager, String phone,
			String intro, Integer typeId, String imgs) {
		super();
		this.centerName = centerName;
		this.createTime = createTime;
		this.address = address;
		this.manager = manager;
		this.phone = phone;
		this.intro = intro;
		this.typeId = typeId;
		this.imgs = imgs;
	}

	public PracticeCenter(Integer id, String centerName, Date createTime, String address, String manager, String phone,
			String intro, Integer typeId, String imgs) {
		super();
		this.id = id;
		this.centerName = centerName;
		this.createTime = createTime;
		this.address = address;
		this.manager = manager;
		this.phone = phone;
		this.intro = intro;
		this.typeId = typeId;
		this.imgs = imgs;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.center_name
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String centerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.create_time
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.address
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.manager
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String manager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.phone
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.intro
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.type_id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column practice_center.imgs
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    private String imgs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.id
     *
     * @return the value of practice_center.id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    
    private List<PracticeInstitute> institutes;
    
    public List<PracticeInstitute> getInstitutes() {
		return institutes;
	}

	public void setInstitutes(List<PracticeInstitute> institutes) {
		this.institutes = institutes;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.id
     *
     * @param id the value for practice_center.id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.center_name
     *
     * @return the value of practice_center.center_name
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getCenterName() {
        return centerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.center_name
     *
     * @param centerName the value for practice_center.center_name
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setCenterName(String centerName) {
        this.centerName = centerName == null ? null : centerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.create_time
     *
     * @return the value of practice_center.create_time
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.create_time
     *
     * @param createTime the value for practice_center.create_time
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.address
     *
     * @return the value of practice_center.address
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.address
     *
     * @param address the value for practice_center.address
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.manager
     *
     * @return the value of practice_center.manager
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.manager
     *
     * @param manager the value for practice_center.manager
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.phone
     *
     * @return the value of practice_center.phone
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.phone
     *
     * @param phone the value for practice_center.phone
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.intro
     *
     * @return the value of practice_center.intro
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.intro
     *
     * @param intro the value for practice_center.intro
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.type_id
     *
     * @return the value of practice_center.type_id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.type_id
     *
     * @param typeId the value for practice_center.type_id
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column practice_center.imgs
     *
     * @return the value of practice_center.imgs
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column practice_center.imgs
     *
     * @param imgs the value for practice_center.imgs
     *
     * @mbg.generated Wed Apr 01 10:00:43 CST 2020
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }
}