package cc.sjzd.dao;

import org.apache.ibatis.jdbc.SQL;

import cc.sjzd.entity.PracticeInstitute;

public class PracticeInstituteSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_institute
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String insertSelective(PracticeInstitute record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("practice_institute");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getInstituteName() != null) {
            sql.VALUES("institute_name", "#{instituteName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getManager() != null) {
            sql.VALUES("manager", "#{manager,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getIntro() != null) {
            sql.VALUES("intro", "#{intro,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.VALUES("type_id", "#{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getCenterId() != null) {
            sql.VALUES("center_id", "#{centerId,jdbcType=INTEGER}");
        }
        
        if (record.getImgs() != null) {
            sql.VALUES("imgs", "#{imgs,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_institute
     *
     * @mbg.generated Wed Apr 01 10:01:13 CST 2020
     */
    public String updateByPrimaryKeySelective(PracticeInstitute record) {
        SQL sql = new SQL();
        sql.UPDATE("practice_institute");
        
        if (record.getInstituteName() != null) {
            sql.SET("institute_name = #{instituteName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getManager() != null) {
            sql.SET("manager = #{manager,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getIntro() != null) {
            sql.SET("intro = #{intro,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.SET("type_id = #{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getCenterId() != null) {
            sql.SET("center_id = #{centerId,jdbcType=INTEGER}");
        }
        
        if (record.getImgs() != null) {
            sql.SET("imgs = #{imgs,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}