package cc.sjzd.dao;

import org.apache.ibatis.jdbc.SQL;

import cc.sjzd.entity.PracticeType;

public class PracticeTypeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_type
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public String insertSelective(PracticeType record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("practice_type");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTypeName() != null) {
            sql.VALUES("type_name", "#{typeName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_type
     *
     * @mbg.generated Wed Apr 01 10:07:53 CST 2020
     */
    public String updateByPrimaryKeySelective(PracticeType record) {
        SQL sql = new SQL();
        sql.UPDATE("practice_type");
        
        if (record.getTypeName() != null) {
            sql.SET("type_name = #{typeName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}