package cc.sjzd.dao;

import org.apache.ibatis.jdbc.SQL;

import cc.sjzd.entity.PracticeStation;

public class PracticeStationSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_station
     *
     * @mbg.generated Wed Apr 01 10:14:18 CST 2020
     */
    public String insertSelective(PracticeStation record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("practice_station");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getStationName() != null) {
            sql.VALUES("station_name", "#{stationName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=DATE}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getManager() != null) {
            sql.VALUES("manager", "#{manager,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getIntro() != null) {
            sql.VALUES("intro", "#{intro,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.VALUES("type_id", "#{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getCenterId() != null) {
            sql.VALUES("center_id", "#{centerId,jdbcType=INTEGER}");
        }
        
        if (record.getInstituteId() != null) {
            sql.VALUES("institute_id", "#{instituteId,jdbcType=INTEGER}");
        }
        
        if (record.getImgs() != null) {
            sql.VALUES("imgs", "#{imgs,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table practice_station
     *
     * @mbg.generated Wed Apr 01 10:14:18 CST 2020
     */
    public String updateByPrimaryKeySelective(PracticeStation record) {
        SQL sql = new SQL();
        sql.UPDATE("practice_station");
        
        if (record.getStationName() != null) {
            sql.SET("station_name = #{stationName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=DATE}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getManager() != null) {
            sql.SET("manager = #{manager,jdbcType=VARCHAR}");
        }
        
        if (record.getPhone() != null) {
            sql.SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getIntro() != null) {
            sql.SET("intro = #{intro,jdbcType=VARCHAR}");
        }
        
        if (record.getTypeId() != null) {
            sql.SET("type_id = #{typeId,jdbcType=INTEGER}");
        }
        
        if (record.getCenterId() != null) {
            sql.SET("center_id = #{centerId,jdbcType=INTEGER}");
        }
        
        if (record.getInstituteId() != null) {
            sql.SET("institute_id = #{instituteId,jdbcType=INTEGER}");
        }
        
        if (record.getImgs() != null) {
            sql.SET("imgs = #{imgs,jdbcType=LONGVARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}