package cc.wmhhb.entity;

import java.util.Date;

public class BlackList {
	
	
    public BlackList() {
		super();
	}

	public BlackList(Integer id, String img, String content, String link, String address, Date createTime,
			Integer createBy, Integer dislikes) {
		super();
		this.id = id;
		this.img = img;
		this.content = content;
		this.link = link;
		this.address = address;
		this.createTime = createTime;
		this.createBy = createBy;
		this.dislikes = dislikes;
	}

	public BlackList(String img, String content, String link, String address, Date createTime, Integer createBy,
			Integer dislikes) {
		super();
		this.img = img;
		this.content = content;
		this.link = link;
		this.address = address;
		this.createTime = createTime;
		this.createBy = createBy;
		this.dislikes = dislikes;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.id
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.img
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.content
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.link
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.address
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.create_time
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.create_by
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column black_list.dislikes
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    private Integer dislikes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.id
     *
     * @return the value of black_list.id
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.id
     *
     * @param id the value for black_list.id
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.img
     *
     * @return the value of black_list.img
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.img
     *
     * @param img the value for black_list.img
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.content
     *
     * @return the value of black_list.content
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.content
     *
     * @param content the value for black_list.content
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.link
     *
     * @return the value of black_list.link
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.link
     *
     * @param link the value for black_list.link
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.address
     *
     * @return the value of black_list.address
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.address
     *
     * @param address the value for black_list.address
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.create_time
     *
     * @return the value of black_list.create_time
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.create_time
     *
     * @param createTime the value for black_list.create_time
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.create_by
     *
     * @return the value of black_list.create_by
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.create_by
     *
     * @param createBy the value for black_list.create_by
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column black_list.dislikes
     *
     * @return the value of black_list.dislikes
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public Integer getDislikes() {
        return dislikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column black_list.dislikes
     *
     * @param dislikes the value for black_list.dislikes
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    public void setDislikes(Integer dislikes) {
        this.dislikes = dislikes;
    }
}