package cc.hdgg.entity;

import java.util.Date;

public class ActivitySignup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.activity_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.user_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.create_time
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.create_by
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.name
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.age
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.head_img
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private String headImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.grade
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.phone
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_signup.address
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.id
     *
     * @return the value of activity_signup.id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    //对应活动类
    private ActivityNotice notice;
    
    
    public ActivityNotice getNotice() {
		return notice;
	}

	public void setNotice(ActivityNotice notice) {
		this.notice = notice;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.id
     *
     * @param id the value for activity_signup.id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.activity_id
     *
     * @return the value of activity_signup.activity_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.activity_id
     *
     * @param activityId the value for activity_signup.activity_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.user_id
     *
     * @return the value of activity_signup.user_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.user_id
     *
     * @param userId the value for activity_signup.user_id
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.create_time
     *
     * @return the value of activity_signup.create_time
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.create_time
     *
     * @param createTime the value for activity_signup.create_time
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.create_by
     *
     * @return the value of activity_signup.create_by
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.create_by
     *
     * @param createBy the value for activity_signup.create_by
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.name
     *
     * @return the value of activity_signup.name
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.name
     *
     * @param name the value for activity_signup.name
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.age
     *
     * @return the value of activity_signup.age
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.age
     *
     * @param age the value for activity_signup.age
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.head_img
     *
     * @return the value of activity_signup.head_img
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public String getHeadImg() {
        return headImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.head_img
     *
     * @param headImg the value for activity_signup.head_img
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg == null ? null : headImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.grade
     *
     * @return the value of activity_signup.grade
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.grade
     *
     * @param grade the value for activity_signup.grade
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.phone
     *
     * @return the value of activity_signup.phone
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.phone
     *
     * @param phone the value for activity_signup.phone
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_signup.address
     *
     * @return the value of activity_signup.address
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_signup.address
     *
     * @param address the value for activity_signup.address
     *
     * @mbg.generated Thu Apr 30 18:17:02 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}