package cc.hdgg.entity;

import java.util.Date;

public class ActivityNotice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.id
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.title
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.address
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.participate_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Integer participateNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.total_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.contacts
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.phone
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.imgs
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String imgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.start_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.end_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.create_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.create_by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.update_tiem
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Date updateTiem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.update-by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_notice.content
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.id
     *
     * @return the value of activity_notice.id
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.id
     *
     * @param id the value for activity_notice.id
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.title
     *
     * @return the value of activity_notice.title
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.title
     *
     * @param title the value for activity_notice.title
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.address
     *
     * @return the value of activity_notice.address
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.address
     *
     * @param address the value for activity_notice.address
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.participate_num
     *
     * @return the value of activity_notice.participate_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Integer getParticipateNum() {
        return participateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.participate_num
     *
     * @param participateNum the value for activity_notice.participate_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setParticipateNum(Integer participateNum) {
        this.participateNum = participateNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.total_num
     *
     * @return the value of activity_notice.total_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.total_num
     *
     * @param totalNum the value for activity_notice.total_num
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.contacts
     *
     * @return the value of activity_notice.contacts
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.contacts
     *
     * @param contacts the value for activity_notice.contacts
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.phone
     *
     * @return the value of activity_notice.phone
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.phone
     *
     * @param phone the value for activity_notice.phone
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.imgs
     *
     * @return the value of activity_notice.imgs
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.imgs
     *
     * @param imgs the value for activity_notice.imgs
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.start_time
     *
     * @return the value of activity_notice.start_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.start_time
     *
     * @param startTime the value for activity_notice.start_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.end_time
     *
     * @return the value of activity_notice.end_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.end_time
     *
     * @param endTime the value for activity_notice.end_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.create_time
     *
     * @return the value of activity_notice.create_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.create_time
     *
     * @param createTime the value for activity_notice.create_time
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.create_by
     *
     * @return the value of activity_notice.create_by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.create_by
     *
     * @param createBy the value for activity_notice.create_by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.update_tiem
     *
     * @return the value of activity_notice.update_tiem
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Date getUpdateTiem() {
        return updateTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.update_tiem
     *
     * @param updateTiem the value for activity_notice.update_tiem
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setUpdateTiem(Date updateTiem) {
        this.updateTiem = updateTiem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.update-by
     *
     * @return the value of activity_notice.update-by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.update-by
     *
     * @param updateBy the value for activity_notice.update-by
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_notice.content
     *
     * @return the value of activity_notice.content
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_notice.content
     *
     * @param content the value for activity_notice.content
     *
     * @mbg.generated Wed Apr 29 11:06:32 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}