package cc.wmhhb.dao;

import cc.wmhhb.entity.BlackList;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface BlackListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @Delete({
        "delete from black_list",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @Insert({
        "insert into black_list (id, img, ",
        "content, link, address, ",
        "create_time, create_by, ",
        "dislikes)",
        "values (#{id,jdbcType=INTEGER}, #{img,jdbcType=VARCHAR}, ",
        "#{content,jdbcType=VARCHAR}, #{link,jdbcType=VARCHAR}, #{address,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createBy,jdbcType=INTEGER}, ",
        "#{dislikes,jdbcType=INTEGER})"
    })
    int insert(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @InsertProvider(type=BlackListSqlProvider.class, method="insertSelective")
    int insertSelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @Select({
        "select",
        "id, img, content, link, address, create_time, create_by, dislikes",
        "from black_list",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results(id="blackMap",value={
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="img", property="img", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="link", property="link", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="create_by", property="createBy", jdbcType=JdbcType.INTEGER),
        @Result(column="dislikes", property="dislikes", jdbcType=JdbcType.INTEGER)
    })
    BlackList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @UpdateProvider(type=BlackListSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BlackList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table black_list
     *
     * @mbg.generated Sun May 10 16:33:46 CST 2020
     */
    @Update({
        "update black_list",
        "set img = #{img,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "link = #{link,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "create_by = #{createBy,jdbcType=INTEGER},",
          "dislikes = #{dislikes,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BlackList record);
    
    //查找全部的方法
    @Select({
    	"select",
        "id, img, content, link, address, create_time, create_by, dislikes",
        "from black_list"
    })
    @ResultMap("blackMap")
    List<BlackList> selectAll();
    
}